#!/usr/bin/perl
use warnings;
use strict;

%HoH = (
    password => {
        opensesame => "login=granted",
        
    },
    #jetsons => {
    #    lead      => "george",
    #    wife      => "jane",
    #    "his boy" => "elroy",
    #},
    #simpsons => {
    #    lead => "homer",
    #    wife => "marge",
    #    kid  => "bart",
    #},
);
